/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListRouteImport } from './routes/list'
import { Route as FurnitureIndexRouteImport } from './routes/furniture.index'
import { Route as FurnitureItemIdRouteImport } from './routes/furniture.$itemId'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const FurnitureIndexRoute = FurnitureIndexRouteImport.update({
  id: '/furniture/',
  path: '/furniture/',
  getParentRoute: () => rootRouteImport,
} as any)
const FurnitureItemIdRoute = FurnitureItemIdRouteImport.update({
  id: '/furniture/$itemId',
  path: '/furniture/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/furniture/$itemId': typeof FurnitureItemIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/furniture/': typeof FurnitureIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/furniture/$itemId': typeof FurnitureItemIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/furniture': typeof FurnitureIndexRoute
  '/rooms': typeof RoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/list': typeof ListRoute
  '/furniture/$itemId': typeof FurnitureItemIdRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/furniture/': typeof FurnitureIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/list'
    | '/furniture/$itemId'
    | '/rooms/$roomId'
    | '/furniture/'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/list'
    | '/furniture/$itemId'
    | '/rooms/$roomId'
    | '/furniture'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/list'
    | '/furniture/$itemId'
    | '/rooms/$roomId'
    | '/furniture/'
    | '/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListRoute: typeof ListRoute
  FurnitureItemIdRoute: typeof FurnitureItemIdRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  FurnitureIndexRoute: typeof FurnitureIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/furniture/': {
      id: '/furniture/'
      path: '/furniture'
      fullPath: '/furniture/'
      preLoaderRoute: typeof FurnitureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/furniture/$itemId': {
      id: '/furniture/$itemId'
      path: '/furniture/$itemId'
      fullPath: '/furniture/$itemId'
      preLoaderRoute: typeof FurnitureItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListRoute: ListRoute,
  FurnitureItemIdRoute: FurnitureItemIdRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  FurnitureIndexRoute: FurnitureIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
